# for easy updating/upgrading
alias upgrade='sudo apt update && sudo apt upgrade'
alias update='sudo apt update'
alias install='sudo apt install'
alias asd='mesleep'
alias i3conf='cd ~/dotfiles && nvim i3/.config/regolith/i3/config'
alias pipes.sh='pipes.sh -R -r 0 -s 6 -p 15 -f 100'
alias ll='ls -lAh'
alias tasks='task list sort:project'
alias wttr='curl wttr.in/Oslo?lang=en'
alias exp='expressvpn'
alias bt='bluetoothctl'
alias website='ssh root@51.15.134.113'
alias mongotime='docker run -d -p 27017:27017 mongo:4.0.12'
